albus/config/routes.rb
Rails.application.routes.draw do
  resources :buses
  resources :drivers
  resources :employees
  resources :login
  resources :spots
  post 'select_driver', to:'buses#select_driver'
  post 'select_line', to:'buses#select_line'
  post 'remove_line', to:'buses#remove_line'
  post 'remove_driver', to:'buses#remove_driver'
  get 'lines', to: 'lines#index'
  post 'lines', to: 'lines#create'
  put 'lines/:id', to: 'lines#update'
  get 'lines/:id', to: 'lines#show'
  delete 'lines/:id', to: 'lines#destroy'
  get 'home', to: 'application#index'
  get '/', to: 'login#new'
  get 'logout', to: 'login#logout'
  root 'login#new'
  get 'main', to: 'application#main'
  get 'services/stops', to: 'services#stops'
  get 'services/lines', to: 'services#lines'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

albus/app/models/driver.rb
class Driver < ApplicationRecord
  has_one :bus
  
  validates :name, :cpf, :email, presence: true
end

albus/app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  before_action :set_driver, only: [:show, :edit, :update, :destroy]

  before_action :authorize, except: [:new, :create]

  # GET /motorista
  # GET /motorista.json
  def index
    @drivers = Driver.all
  end

  # GET /motorista/1
  # GET /motorista/1.json
  def show
    if(@driver==nil)
      redirect_to drivers_path, notice: 'Driver id not found'
    end
  end

  # GET /motorista/new
  def new
    @driver = Driver.new
  end

  # GET /motorista/1/edit
  def edit
  end

  # POST /motorista
  # POST /motorista.json
  def create
    @driver = Driver.new(driver_params)

    respond_to do |format|
      if @driver.save
        format.html { redirect_to drivers_path, notice: 'Driver was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motorista/1
  # PATCH/PUT /motorista/1.json
  def update
    respond_to do |format|
      if(@driver==nil)
        format.html { redirect_to drivers_path, notice: 'Driver id not found' }
      elsif @driver.update(driver_params)
        format.html { redirect_to @driver, notice: 'Driver was successfully updated.' }
        format.json { render :show, status: :ok, location: @driver }
      else
        format.html { render :edit }
        format.json { render json: @driver.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motorista/1
  # DELETE /motorista/1.json
  def destroy
    @driver.destroy
    respond_to do |format|
      format.html { redirect_to drivers_url, notice: 'Driver was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_driver
      @driver = Driver.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def driver_params
      params.require(:driver).permit(:name, :cpf, :email, :telephone)
    end
end

albus/app/helpers/drivers_helper.rb
module DriversHelper
end

albus/app/views/drivers/_form.html.erb
<%= form_for(driver) do |f| %>
  <% if driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(driver.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% driver.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="form-group"><%= f.text_field :name, class: 'form-control', placeholder: "Nome", required: true %></div>
  <div class="form-group"><%= f.text_field :cpf, class: 'form-control', placeholder: "CPF", required: true %></div>
  <div class="form-group"><%= f.text_field :email, class: 'form-control', placeholder: "Email", required: true %></div>
  <div class="form-group"><%= f.text_field :telephone, class: 'form-control', placeholder: "Telefone", required: true %></div>
	<div class="form-group"><%= f.submit class:'form-control btn btn-primary' %></div>
<% end %>

albus/app/views/drivers/edit.html.erb
<% content_for :breadcrumbs do %>
    <li class="breadcrumb-item">
      <%= link_to 'Motoristas', drivers_path%>
    </li>
    <li class="breadcrumb-item active">
      Editar
    </li>
<% end %>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= render 'form', driver: @driver %>
  </div>
</div>

albus/app/views/drivers/index.html.erb
<% content_for :breadcrumbs do %>
    <li class="breadcrumb-item active">
      Motoristas
    </li>
<% end %>
<div class="text left">
  <%= link_to "Novo",new_driver_path, :class=>"btn btn-primary" %>
</div>
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
                <th>Nome</th>
                <th>CPF</th>
                <th>Email</th>
                <th>Telefone</th>
                <th colspan="3">Ações</th>
          </tr>
        </thead>

        <tbody>
          <%= content_tag_for(:tr, @drivers) do |driver| %>
                <td><%= driver.name %></td>
                <td><%= driver.cpf %></td>
                <td><%= driver.email %></td>
                <td><%= driver.telephone %></td>
                <td><%= link_to 'Ver', driver %></td>
            <td><%= link_to 'Editar', edit_driver_path(driver) %></td>
            <td><%= button_to 'Deletar', driver, method: :delete, data: { confirm: 'Tem certeza?' }, class:"btn btn-danger btn-sm" %></td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

albus/app/views/drivers/index2.html.erb
<p id="notice"><%= notice %></p>
<div class="list">
  <h3>Motoristas</h3>
  <% @drivers.each do |driver| %>
    <div class="item">
      <div class="text left">
        <h4><%= driver.name %></h4>
        <p><%= driver.email %></p>
        <p><%= driver.telephone %></p>
        <!--<a href="#" class="more">Find out more</a> </div>-->
        <div class="cl">&nbsp;</div>
      </div>
    </div>
  <% end %>
  <div id="icons-container" class="item">
    <div class="text left">
      <%= link_to image_tag("add-user.png", class: "icon"), new_driver_path %>
    </div>
  </div>
</div>
<br>

albus/app/views/drivers/new.html.erb
<% content_for :breadcrumbs do %>
    <li class="breadcrumb-item">
      <%= link_to 'Motoristas', drivers_path%>
    </li>
    <li class="breadcrumb-item active">
      Novo
    </li>
<% end %>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= render 'form', driver: @driver %>
  </div>
</div>

albus/app/views/drivers/show.html.erb
<% content_for :breadcrumbs do %>
    <li class="breadcrumb-item">
      <%= link_to 'Motoristas', drivers_path%>
    </li>
    <li class="breadcrumb-item active">
      Visualizar
    </li>
<% end %>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @driver.name %></dd>

  <dt>CPF:</dt>
  <dd><%= @driver.cpf %></dd>

  <dt>Email:</dt>
  <dd><%= @driver.email %></dd>

  <dt>Telefone:</dt>
  <dd><%= @driver.telephone %></dd>
  <%= link_to edit_driver_path(@driver), class: 'btn btn-primary' do %>
    Editar
  <% end %>
</dl>