albus/config/routes.rb
Rails.application.routes.draw do
  resources :buses
  resources :drivers
  resources :employees
  resources :login
  resources :spots
  post 'select_driver', to:'buses#select_driver'
  post 'select_line', to:'buses#select_line'
  post 'remove_line', to:'buses#remove_line'
  post 'remove_driver', to:'buses#remove_driver'
  get 'lines', to: 'lines#index'
  post 'lines', to: 'lines#create'
  put 'lines/:id', to: 'lines#update'
  get 'lines/:id', to: 'lines#show'
  delete 'lines/:id', to: 'lines#destroy'
  get 'home', to: 'application#index'
  get '/', to: 'login#new'
  get 'logout', to: 'login#logout'
  root 'login#new'
  get 'main', to: 'application#main'
  get 'services/stops', to: 'services#stops'
  get 'services/lines', to: 'services#lines'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

albus/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def index
    render 'index'
  end

  def authorize
    unless session[:user_id]
      redirect_to root_url
    end
  end

end

albus/app/helpers/application_helper.rb
module ApplicationHelper
end

albus/app/views/application/_footer.html.erb
<div id="footer">
  <p class="left">Copyright &copy; 2017, alBus, All Rights Reserved</p>
  <div class="cl"></div>
</div>

albus/app/views/application/_headbar.html.erb
<div class="shell">
  <div class="border">
    <div id="header">
      <h1 id="logo"><a href="#" class="notext">alBus</a></h1>
      <div class="cl">&nbsp;</div>
    </div>
    <%= render 'menubar' %> 

albus/app/views/application/_headbar_login.html.erb
<div class="shell">
  <div class="border">
    <div id="header">
      <h1 id="logo"><a href="#" class="notext">alBus</a></h1>
      <div class="cl">&nbsp;</div>
    </div>

albus/app/views/application/_menubar.html.erb
<div id="navigation">
  <ul>
    <li><%=link_to "Home", home_path %></li>
    <li><%=link_to "Funcionários", employees_path %></li>
    <li><%=link_to "Motoristas", drivers_path %></li>
    <li><%=link_to "Ônibus", buses_path %></li>
    <li><a href="#">Rota</a></li>
  </ul>
  <div class="cl">&nbsp;</div>
</div>

albus/app/views/application/index.html.erb
<div class="highlight">
  <h3>Welcome Note</h3>
  <img src="highlight.gif" alt="" class="right" />
  <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s.</p>
</div>
<div class="list">
  <h3>Latest projects</h3>
  <div class="item">
    <div class="image left"> <a href="#"><img src="project01.jpg" alt="" /></a> </div>
    <div class="text left">
      <h4>simply dummy title</h4>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is</p>
      <a href="#" class="more">Find out more</a> </div>
    <div class="cl">&nbsp;</div>
  </div>
  <div class="item">
    <div class="image left"> <a href="#"><img src="project02.jpg" alt="" /></a> </div>
    <div class="text left">
      <h4>simply dummy title</h4>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is</p>
      <a href="#" class="more">Find out more</a> </div>
    <div class="cl">&nbsp;</div>
  </div>
  <div class="item">
    <div class="image left"> <a href="#"><img src="project03.jpg" alt="" /></a> </div>
    <div class="text left">
      <h4>simply dummy title</h4>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is</p>
      <a href="#" class="more">Find out more</a> </div>
    <div class="cl">&nbsp;</div>
  </div>
  <div class="item">
    <div class="image left"> <a href="#"><img src="project04.jpg" alt="" /></a> </div>
    <div class="text left">
      <h4>simply dummy title</h4>
      <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is</p>
      <a href="#" class="more">Find out more</a> </div>
    <div class="cl">&nbsp;</div>
  </div>
</div>