albus/config/routes.rb
Rails.application.routes.draw do
  resources :buses
  resources :drivers
  resources :employees
  resources :login
  resources :spots
  post 'select_driver', to:'buses#select_driver'
  post 'select_line', to:'buses#select_line'
  post 'remove_line', to:'buses#remove_line'
  post 'remove_driver', to:'buses#remove_driver'
  get 'lines', to: 'lines#index'
  post 'lines', to: 'lines#create'
  put 'lines/:id', to: 'lines#update'
  get 'lines/:id', to: 'lines#show'
  delete 'lines/:id', to: 'lines#destroy'
  get 'home', to: 'application#index'
  get '/', to: 'login#new'
  get 'logout', to: 'login#logout'
  root 'login#new'
  get 'main', to: 'application#main'
  get 'services/stops', to: 'services#stops'
  get 'services/lines', to: 'services#lines'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

albus/app/views/layouts/applayout.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Starter Template for Bootstrap</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
  <script src="https://use.fontawesome.com/0dc9eeca2d.js"></script>

</head>
<body class="fixed-nav sticky-footer bg-dark sidenav-toggled" id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <a class="navbar-brand" href="index.html">Albus</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
              <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Funcionários">
                  <%= link_to employees_path, :class=>"nav-link" do %>
                    <i class="fa fa-fw fa-address-book"></i>
                    <span class="nav-link-text">Funcionários</span>
                  <% end %>
                  <!--<li><%=link_to "Motoristas", drivers_path %></li>
                  <li><%=link_to "Ônibus", buses_path %></li>-->
              </li>
              <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Motoristas">
                <%= link_to drivers_path, :class=>"nav-link" do %>
                  <i class="fa fa-fw fa-drivers-license"></i>
                  <span class="nav-link-text">Motoristas</span>
                <% end %>
              </li>
              <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Ônibus">
                <%= link_to buses_path, :class=>"nav-link" do %>
                  <i class="fa fa-fw fa-bus"></i>
                  <span class="nav-link-text">Ônibus</span>
                <% end %>
              </li>
              <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Rotas">
                <%= link_to spots_path, :class=>"nav-link" do %>
                  <i class="fa fa-fw fa-road"></i>
                  <span class="nav-link-text">Rotas</span>
                <% end %>
                <!--<ul class="sidenav-second-level collapse" id="collapseComponents">
                  <li>
                    <a href="navbar.html">Navbar</a>
                  </li>
                  <li>
                    <a href="cards.html">Cards</a>
                  </li>
                </ul>-->
              </li>
            </ul>
            <ul class="navbar-nav sidenav-toggler">
              <li class="nav-item">
                <a class="nav-link text-center" id="sidenavToggler">
                  <i class="fa fa-fw fa-angle-left"></i>
                </a>
              </li>
            </ul>
            <!-- top bar -->
            <ul class="navbar-nav ml-auto">

              <li class="nav-item">
                <form class="form-inline my-2 my-lg-0 mr-lg-2">
                  <div class="input-group">
                    <input class="form-control" type="text" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-primary" type="button">
                        <i class="fa fa-search"></i>
                      </button>
                    </span>
                  </div>
                </form>
              </li>
              <li class="nav-item">
                <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                  <i class="fa fa-fw fa-sign-out"></i>Logout</a>
              </li>
            </ul>
          </div>
        </nav>
    <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <%= yield :breadcrumbs %>
      </ol>


      <%= yield %>

    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Your Website 2017</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>


    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield :scripts %>
  </div>
  <!-- <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

  </div> -->

</body>
</html>

albus/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Albus</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= javascript_tag "window._token = '#{form_authenticity_token}'" %>
  <script src="https://use.fontawesome.com/0dc9eeca2d.js"></script>
</head>
<body class="fixed-nav sticky-footer bg-dark sidenav-toggled" id="page-top">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <%= link_to root_url, :class=>"navbar-brand" do %>
        Albus
        <% end%>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
            <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Funcionários">
                <%= link_to employees_path, :class=>"nav-link" do %>
                  <i class="fa fa-fw fa-address-book"></i>
                  <span class="nav-link-text">Funcionários</span>
                <% end %>
                <!--<li><%=link_to "Motoristas", drivers_path %></li>
                <li><%=link_to "Ônibus", buses_path %></li>-->
            </li>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Motoristas">
            <%= link_to drivers_path, :class=>"nav-link" do %>
              <i class="fa fa-fw fa-drivers-license"></i>
              <span class="nav-link-text">Motoristas</span>
            <% end %>
          </li>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Ônibus">
            <%= link_to buses_path, :class=>"nav-link" do %>
              <i class="fa fa-fw fa-bus"></i>
              <span class="nav-link-text">Ônibus</span>
            <% end %>
          </li>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Paradas">
            <%= link_to spots_path, :class=>"nav-link" do %>
              <i class="fa fa-fw fa-flag"></i>
              <span class="nav-link-text">Paradas</span>
            <% end %>
          </li>
          <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Rotas">
            <%= link_to lines_path, :class=>"nav-link" do %>
              <i class="fa fa-fw fa-road"></i>
              <span class="nav-link-text">Rotas</span>
            <% end %>
          </li>
        </ul>
        <ul class="navbar-nav sidenav-toggler">
          <li class="nav-item">
            <a class="nav-link text-center" id="sidenavToggler">
              <i class="fa fa-fw fa-angle-left"></i>
            </a>
          </li>
        </ul>
        <!-- top bar -->
        <ul class="navbar-nav ml-auto">

            <li class="nav-item">
              <form class="form-inline my-2 my-lg-0 mr-lg-2">
                <div class="input-group">
                  <input class="form-control" type="text" placeholder="Search for...">
                  <span class="input-group-btn">
                    <button class="btn btn-primary" type="button">
                      <i class="fa fa-search"></i>
                    </button>
                  </span>
                </div>
              </form>
            </li>

            <% if session[:user_id] %>
            <li class="nav-item">
              <%= link_to logout_path, class:"nav-link" do %>
                <i class="fa fa-fw fa-sign-out"></i>Logout</a>
            <% end %>
            <% end %>
          </ul>
        </div>
      </nav>
    <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <%= yield :breadcrumbs %>
      </ol>


      <%= yield %>

    </div>
    <!-- /.container-fluid-->
    <!-- /.content-wrapper-->
    <footer class="sticky-footer">
      <div class="container">
        <div class="text-center">
          <small>Copyright © Your Website 2017</small>
        </div>
      </div>
    </footer>
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
      <i class="fa fa-angle-up"></i>
    </a>


    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= yield :scripts %>
  </div>
  <!-- <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

  </div> -->
</body>
</html>