albus/config/routes.rb
Rails.application.routes.draw do
  resources :buses
  resources :drivers
  resources :employees
  resources :login
  resources :spots
  post 'select_driver', to:'buses#select_driver'
  post 'select_line', to:'buses#select_line'
  post 'remove_line', to:'buses#remove_line'
  post 'remove_driver', to:'buses#remove_driver'
  get 'lines', to: 'lines#index'
  post 'lines', to: 'lines#create'
  put 'lines/:id', to: 'lines#update'
  get 'lines/:id', to: 'lines#show'
  delete 'lines/:id', to: 'lines#destroy'
  get 'home', to: 'application#index'
  get '/', to: 'login#new'
  get 'logout', to: 'login#logout'
  root 'login#new'
  get 'main', to: 'application#main'
  get 'services/stops', to: 'services#stops'
  get 'services/lines', to: 'services#lines'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

albus/app/controllers/buses_controller.rb
class BusesController < ApplicationController
  before_action :set_bus, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:new, :create]

  # GET /onibuses
  # GET /onibuses.json

  def index
    @buses = Bus.all
  end

  # GET /onibuses/1
  # GET /onibuses/1.json
  def show
    if @bus==nil
      redirect_to buses_path, notice: 'Ônibus não encontrado.'
    end
    @drivers = Driver.all
    @lines = Line.all
    @driver = @bus.driver
    @line = @bus.line
    @showDrivers = params[:show_drivers]
    @showLines = params[:show_lines]
  end

  # GET /onibuses/new
  def new
    @bus = Bus.new
  end

  # GET /onibuses/1/edit
  def edit
  end

  # POST /onibuses
  # POST /onibuses.json
  def create
    @bus = Bus.new(bus_params)

    respond_to do |format|
      if @bus.save
        format.html { redirect_to buses_path, notice: 'Bus was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /onibuses/1
  # PATCH/PUT /onibuses/1.json
  def update
    respond_to do |format|
      if(@bus==nil)
        format.html { redirect_to buses_path, notice: 'Bus id not found' }
      elsif @bus.update(bus_params)
        format.html { redirect_to @bus, notice: 'Bus was successfully updated.' }
        format.json { render :show, status: :ok, location: @bus }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /onibuses/1
  # DELETE /onibuses/1.json
  def destroy
    @bus.destroy
    respond_to do |format|
      format.html { redirect_to buses_url, notice: 'Bus was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def select_driver
    respond_to do |format|
      @bus = Bus.find(params[:bus_id])
      @driver = Driver.find(params[:driver_id])
      @bus.driver = @driver

      if @bus.save
        format.html { redirect_to @bus, notice: 'Motorista selecionado com sucesso!' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  def select_line
    respond_to do |format|
      @bus = Bus.find(params[:bus_id])
      @line = Line.find(params[:line_id])
      @bus.line = @line

      if @bus.save
        format.html { redirect_to @bus, notice: 'Motorista selecionado com sucesso!' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_driver
    respond_to do |format|
      @bus = Bus.find(params[:bus_id])
      @bus.driver = nil

      if @bus.save
        format.html { redirect_to @bus, notice: 'Motorista retirado com sucesso!' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  def remove_line
    respond_to do |format|
      @bus = Bus.find(params[:bus_id])
      @bus.line = nil

      if @bus.save
        format.html { redirect_to @bus, notice: 'Motorista retirado com sucesso!' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @bus.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bus
      @bus = Bus.find_by_id(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bus_params
      params.require(:bus).permit(:plate, :model, :nSeats)
    end
end

albus/app/helpers/buses_helper.rb
module BusesHelper
end

albus/app/views/buses/_form.html.erb
<%= form_for(bus) do |f| %>
  <% if bus.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bus.errors.count, "error") %> prohibited this bus from being saved:</h2>

      <ul>
      <% bus.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
	<div class="form-group">
		<%= f.text_field :plate, class: 'form-control', placeholder: "Placa", required: true %>
	</div>
	<div class="form-group">
  	<%= f.text_field :model, class: 'form-control', placeholder: "Modelo", required: true %>
	</div>
	<div class="form-group">
		<%= f.number_field :nSeats, class: 'form-control', placeholder: "Número de Acentos", required: true %>
	</div>
	<div class="form-group">
		<%= f.submit class:'form-control btn btn-primary' %>
	</div>
<% end %>

albus/app/views/buses/edit.html.erb
<% content_for :breadcrumbs do %>
    <li class="breadcrumb-item">
      <%= link_to 'Ônibus', buses_path%>
    </li>
    <li class="breadcrumb-item active">
      Editar
    </li>
<% end %>

<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= render 'form', bus: @bus %>
  </div>
</div>

albus/app/views/buses/index.html.erb
<% content_for :breadcrumbs do %>
    <li class="breadcrumb-item active">
      Ônibus
    </li>
<% end %>
<div class="text left">
  <%= link_to "Novo",new_bus_path, :class=>"btn btn-primary" %>
</div>
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
                <th>Placa</th>
                <th>Modelo</th>
                <th>Acentos</th>
                <th colspan="3">Ações</th>
          </tr>
        </thead>

        <tbody>
          <%= content_tag_for(:tr, @buses) do |bus| %>
                <td><%= bus.plate %></td>
                <td><%= bus.model %></td>
                <td><%= bus.nSeats %></td>
                <td><%= link_to 'Ver', bus %></td>
            <td><%= link_to 'Editar', edit_bus_path(bus) %></td>
            <td><%= button_to 'Deletar', bus, method: :delete, data: { confirm: 'Tem certeza?' }, class:"btn btn-danger btn-sm" %></td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

albus/app/views/buses/index2.html.erb
<p id="notice"><%= notice %></p>
<div class="list">
  <h3>Ônibus</h3>
  <% @buses.each do |bus| %>
    <div class="item">
      <div class="text left">
        <h4>Placa: <%= bus.plate %></h4>
        <p>Modelo: <%= bus.model %></p>
        <p>Número de acentos: <%= bus.nSeats %></p>
        <!--<a href="#" class="more">Find out more</a> </div>-->
        <div class="cl">&nbsp;</div>
      </div>
    </div>
  <% end %>
  <div id="icons-container" class="item">
    <div class="text left">
      <%= link_to image_tag("add-bus.png", class: "icon"), new_bus_path %>
    </div>
  </div>
</div>
<br>

albus/app/views/buses/new.html.erb
<% content_for :breadcrumbs do %>
    <li class="breadcrumb-item">
      <%= link_to 'Ônibus', buses_path%>
    </li>
    <li class="breadcrumb-item active">
      Novo
    </li>
<% end %>
<div class="row">
  <div class="col-sm-6 offset-sm-3">
    <%= render 'form', bus: @bus %>
  </div>
</div>

albus/app/views/buses/show.html.erb
<% content_for :breadcrumbs do %>
    <li class="breadcrumb-item">
      <%= link_to 'Ônibus', buses_path%>
    </li>
    <li class="breadcrumb-item active">
      Visualizar
    </li>
<% end %>

<dl class="dl-horizontal">
  <dt>Placa:</dt>
  <dd><%= @bus.plate %></dd>

  <dt>Modelo:</dt>
  <dd><%= @bus.model %></dd>

  <dt>Acentos:</dt>
  <dd><%= @bus.nSeats %></dd>
  <%= link_to edit_bus_path(@bus), class: 'btn btn-primary' do %>
    Editar
  <% end %>
  <%= link_to 'Selecionar Motorista', bus_path(@bus, show_drivers: true ), class: 'btn btn-primary' %>
  <%= link_to 'Selecionar Linha', bus_path(@bus, show_lines: true ), class: 'btn btn-primary' %>
</dl>

<h3>Motorista Responsável</h3>
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <% if @driver %>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
                  <th>Nome</th>
                  <th colspan="2">Ações</th>
            </tr>
          </thead>

          <tbody>
              <td><%= @driver.name %></td>
              <td><%= link_to 'Ver', @driver, class:"btn btn-primary", target: :_blank  %></td>
              <td><%= button_to 'Retirar Motorista', {:controller => 'buses', :action => 'remove_driver', :bus_id => @bus.id},:confirm => 'Deseja retirar este motorista deste ônibus?', :method => :post , class:"btn btn-danger btn-sm" %></td>
          </tbody>
        </table>
    </div>
  <% else %>
    <p>Nenhum motorista selecionado para este ônibus</p>
  <% end %>
  </div>
</div>
<h3>Linha Atual</h3>
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <% if @line %>
      <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
                  <th>Nome</th>
                  <th colspan="2">Ações</th>
            </tr>
          </thead>

          <tbody>
              <td><%= @line.name %></td>
              <td><%= button_to 'Retirar linha', {:controller => 'buses', :action => 'remove_line', :bus_id => @bus.id},:confirm => 'Deseja retirar este ônibus desta linha?', :method => :post , class:"btn btn-danger btn-sm" %></td>
          </tbody>
        </table>
    </div>
  <% else %>
    <p>Nenhuma linha selecionada para este ônibus</p>
  <% end %>
  </div>
</div>
<% if @showDrivers %>
<h3>Selecionar Motorista</h3>
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
              <th>Nome</th>
              <th colspan="2">Ações</th>
          </tr>
        </thead>
        <tbody>
          <%= content_tag_for(:tr, @drivers) do |driver| %>
            <td><%= driver.name %></td>
            <td><%= link_to 'Ver', driver, class:"btn btn-primary", target: :_blank  %></td>
            <td><%= button_to 'Selecionar motorista', {:controller => 'buses', :action => 'select_driver', :driver_id => driver.id, :bus_id => @bus.id},:confirm => 'Atribuir este motorista como responsável pelo ônibus?', :method => :post , :class => "btn btn-primary" %></td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% end %>
<% if @showLines %>
<h3>Selecionar nova linha</h3>
<div class="row">
  <div class="col-sm-8 offset-sm-2">
    <div class="table-responsive">
      <table class="table table-striped table-bordered table-hover">
        <thead>
          <tr>
              <th>Nome</th>
              <th colspan="2">Ações</th>
          </tr>
        </thead>
        <tbody>
          <%= content_tag_for(:tr, @lines) do |line| %>
            <td><%= line.name %></td>
            <td><%= button_to 'Selecionar linha', {:controller => 'buses', :action => 'select_line', :line_id => line.id, :bus_id => @bus.id},:confirm => 'Selecionar esta linha para este ônibus?', :method => :post , :class => "btn btn-primary" %></td>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<% end %>